# Refrecnes:
# https://zespia.tw/blog/2015/01/21/continuous-deployment-to-github-with-travis/
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs
# https://github.com/iissnan/theme-next-docs/blob/master/.travis.yml
# http://changyuheng.me/2015/when-hexo-static-site-meets-github-pages-and-travis-ci/

language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm install -g gulp

script:
  - gulp build

after_script:
  - cd public
  - git init
  - git config user.name "karl"
  - git config user.email "i@think-diff.me"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GIT_PAGE_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GIT_PAGE_REF: github.com/zhoujiealex/Test-TravisCI.git
   - secure: "cNeTjYVP4NVPFvQRqOGb9TAtUtLbc3ej1yfNTu7GgVVqc3aSfrvKXCjYGdRzBmXmsk+CPiYIc3IqckOXs5teGef8Ri/W2xenaWgtStxWF2dWNV4cL7/7MvhRlKmWpY+HnV+Egg2ui/arSh4QGxk7JbAGQoUjVEG9mKLVjOOlc6Dr6p6YXbh5+2qoSjl6aR338roL34b2Y3EOKaUWjzSyzkzQZUt3Ipnrpe2F4XMEOpze1gaOQpTu8qj1P3siz6yV7s12ht6Bfg6DySBnwPUqYVazMLRc4Mr1+h0Ai3EF64U6JwG8b4KAcCnDHyVV6I9DnxWocJB8eVSIHRgAehLHD0IKTCvf4gGUwNNf+uQ5E7S9z4cENAkx7XsmJ6/oPL2AJaepG+eTVbJDMi/uhr+cs+UmtLfCII3fFTnImS4XY+WgXIqK0hyQCm3Jod1bEjSvOJvbUJ0oMfMY9ZwG8R3uyaKxjJmiP0xrbldyfYwdIm4D7Rqg+IuQQAdYa8L84igIWQewBJ84timeMbyBmMrirIi9sL1unDCc4bSKECYsUw2uvXsi9INLEnE13iT8TZLv/eWWd/rVts+VZd8U/GA7V+HN0qavJU6pdrG1swj4TlLXN7vpfceAG6VKLZAX/jFoj7SlOYHbLK+V0GIn69JgoKfKpWe2vv4WL8Vh7K6xO5g="