language: node_js

node_js:
- '4'

cache:
  apt: true
  directories:
  - node_modules

env:
  global:
  - GIT_PAGE_REF: github.com/zhoujiealex/zhoujiealex.github.io.git
  - GIT_SSH_PAGE_REF: git@github.com:zhoujiealex/zhoujiealex.github.io.git
  - GIT_SSH_CODING_NET: git@git.coding.net:thinkdiffme/thinkdiffme.git
  - GIT_SSH_CODING_NET_KARLZHOU: git@git.coding.net:thinkdiffme/www.karlzhou.com.git
  - secure: cNeTjYVP4NVPFvQRqOGb9TAtUtLbc3ej1yfNTu7GgVVqc3aSfrvKXCjYGdRzBmXmsk+CPiYIc3IqckOXs5teGef8Ri/W2xenaWgtStxWF2dWNV4cL7/7MvhRlKmWpY+HnV+Egg2ui/arSh4QGxk7JbAGQoUjVEG9mKLVjOOlc6Dr6p6YXbh5+2qoSjl6aR338roL34b2Y3EOKaUWjzSyzkzQZUt3Ipnrpe2F4XMEOpze1gaOQpTu8qj1P3siz6yV7s12ht6Bfg6DySBnwPUqYVazMLRc4Mr1+h0Ai3EF64U6JwG8b4KAcCnDHyVV6I9DnxWocJB8eVSIHRgAehLHD0IKTCvf4gGUwNNf+uQ5E7S9z4cENAkx7XsmJ6/oPL2AJaepG+eTVbJDMi/uhr+cs+UmtLfCII3fFTnImS4XY+WgXIqK0hyQCm3Jod1bEjSvOJvbUJ0oMfMY9ZwG8R3uyaKxjJmiP0xrbldyfYwdIm4D7Rqg+IuQQAdYa8L84igIWQewBJ84timeMbyBmMrirIi9sL1unDCc4bSKECYsUw2uvXsi9INLEnE13iT8TZLv/eWWd/rVts+VZd8U/GA7V+HN0qavJU6pdrG1swj4TlLXN7vpfceAG6VKLZAX/jFoj7SlOYHbLK+V0GIn69JgoKfKpWe2vv4WL8Vh7K6xO5g=

addons:
  ssh_known_hosts:
  - github.com
  - git.coding.net

before_install:
# Decrypt the private key
- openssl aes-256-cbc -K $encrypted_9f8cdcf38d01_key -iv $encrypted_9f8cdcf38d01_iv
  -in .travis/ssh_key.enc -out ~/.ssh/id_rsa -d
# Set the permission of the key
- chmod 600 ~/.ssh/id_rsa
# Start SSH agent
- eval $(ssh-agent)
# Add the private key to the system
- ssh-add ~/.ssh/id_rsa
# Copy SSH config
- cp .travis/ssh_config ~/.ssh/config


install:
- npm install

before_script:
- git submodule update --remote --merge

script:
- gulp build

#after_script:
after_success:
- cd public
- git init
- git config user.name "Karl Zhou"
- git config user.email "i@karlzhou.com"
- git add .
- git commit -m "Update docs"
- git push --force --quiet "https://${GH_TOKEN}@${GIT_PAGE_REF}" master:master
#- git push --force --quiet "${GIT_SSH_PAGE_REF}" master:master
#- git push --force --quiet "${GIT_SSH_CODING_NET}" master:master
- git push --force --quiet "${GIT_SSH_CODING_NET_KARLZHOU}" master:coding-pages
- echo "Try to push baidu_urls.txt" && echo ${baidu_submit_token} && echo ${encrypted_9f8cdcf38d01_iv}
- curl -H 'Content-Type:text/plain' --data-binary @baidu_urls.txt "http://data.zz.baidu.com/urls?site=www.karlzhou.com&token=$baidu_submit_token"


branches:
  only:
  - master

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
  - i@think-diff.me
  - zhoujiealex@gmail.com
  on_success: change
  on_failure: always

# Refrecnes:
# https://zespia.tw/blog/2015/01/21/continuous-deployment-to-github-with-travis/
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs
# https://github.com/iissnan/theme-next-docs/blob/master/.travis.yml
# http://changyuheng.me/2015/when-hexo-static-site-meets-github-pages-and-travis-ci/
